### ISSUE TITLE
Clouds are super bright and yellow?

### ISSUE THREAD

**Issue by J-F2** [Stereo528/DefaultPlus#1]
its as simple as that, the clouds appear bright and yellow with the shader. everything else is awesome.
![2024-01-16_16 54 47](https://github.com/Stereo528/DefaultPlus/assets/96497580/7678ab19-4560-4fa1-ba7c-9dd531793950)

**Comment by Stereo528** [comment]
That's intended (mostly by being annoying to fix, but also with the fiddling i could do the best looking was to leave it, this whole shader is cursed)

**Comment by Stereo528** [comment]
also, I'm not really working on the shader anymore...
